### ISSUE TITLE
use more commonly understood terminology like polymorphism and explain what Zig pattern is used

### ISSUE THREAD

**Issue by matu3ba** [SuperAuguste/zig-design-patterns#3]
See https://en.wikipedia.org/wiki/Polymorphism_(computer_science) and in the table "Examples" there could be brief words what the things does in general terminology, ie comptime/dynamic/static polymorphism etc.

**Comment by SuperAuguste** [comment]
To be honest I think this would confuse more than help people.

- "Polymorphism" is so broad that I could include 500 completely different Zig patterns that perform polymorphism.
- I really don't want to encourage people to think of this in an OOP way; these are not patterns that are meant to be copy-pasted into every other file; I myself have used these incredibly rarely, maybe once or twice in the course of three years.

I'd rather people see the examples and make their own connections / choices rather than connect these to prior connotations that may not be honest, correct, or useful.
